# application-dev.properties

# Oracle Database properties for development
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=taskmagnet
spring.datasource.password=mahedee.net
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1

# JPA/Hibernate Configuration for Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update

# App properties
mahedee.app.jwtSecret= ======================Mahedee=SecretKey===========================
mahedee.app.jwtExpirationMs= 86400000
